# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fbfeaa336427a6a4b65b7ae8b47a5e1c3433265a861da67cfebd24b884f0d59d586eab015b2b90d561f77a3e02ad0db6b4d464acdf73b7e362b03ce78114a13

test:
  secret_key_base: f0b12887b731c2b6a4de3c5c59dcaa338d54db5f590d17dfb89b9c37d937fe436b18e1ef858665f4000816d3868614120ee64569e0a429b705e971851317551f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
